branches:
  only:
    - master

install:
  - docker build --tag tor3proxy .
  - docker run -d -p 1080:1080 tor3proxy
  - docker run -d -p 1081:1080 tor3proxy -u "user100:password100"
  - docker run -d -p 1082:1080 -v $TRAVIS_BUILD_DIR/users:/users tor3proxy

script:
  - ./tests/ips_ne.sh --socks5=1080
  - ./tests/ips_ne.sh --socks5=1081,user=user100:password100
  - ./tests/ips_ne.sh --socks5=1082,user=user:password
