name: Trying Actions

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    name: Building an image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker build
        run: docker build . --file Dockerfile --tag tor3proxy
      - name: Debug if needed
        run: |
          export DEBUG=${DEBUG:-false}
          if [[ "$DEBUG" == "true" ]] ; then
            env
          fi
        env:
          DEBUG: ${{secrets.DEBUG}}
