name: Tests

#on: [push, pull_request]

jobs:
  build:
    name: Building an image
    runs-on: ubuntu-latest

#    services:
#      tor3proxy:
#        image: Dockerfile
#        ports:
#          - 1080:1080

#    strategy:
#      matrix:
#        node: [6, 8, 10]


    steps:
#      - uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node }}

      - name: Debug if needed
        run: |
          export DEBUG=${DEBUG:-false}
          if [[ "$DEBUG" == "true" ]] ; then
            env
          fi
        env:
          DEBUG: ${{ secrets.DEBUG }}

      - name: Checking out the repo
        uses: actions/checkout@master
#         with:
#           ref: ${{ github.ref }}

#      - name: Docker build
#        run: docker build . --file Dockerfile --tag tor3proxy

#      - name: Run container
#        run: docker run -d -p 1080:1080 --rm tor3proxy

#      - name: Run container
#        run: docker run -d -p 1081:1080 --rm tor3proxy

#      - name: Run container
#        run: docker run -d -p 1082:1080 --rm tor3proxy

      - name: Direct requests give same IPs
        run: |
          ip1=$(./utils/get_ip.sh)
          ip2=$(./utils/get_ip.sh)
          echo comparing "$ip1" and "$ip2"...
          [[ "$ip1" != "$ip2" ]] && exit 1

      - name: Check anonymous proxy working
        run: |
          ip1=$(./utils/get_ip.sh)
          ip2=$(./utils/get_ip.sh --proxy 1080)
          echo comparing "$ip1" and "$ip2"...
          [[ "$ip1" != "$ip2" ]] && exit 1
