name: TestTest

on: [push, pull_request]

jobs:
  build:
    name: Building an image
    runs-on: ubuntu-latest

    steps:
      - name: Debug if needed
        run: |
          export DEBUG=${DEBUG:-false}
          if [[ "$DEBUG" == "true" ]] ; then
            env
          fi
        env:
          DEBUG: ${{ secrets.DEBUG }}

      - name: Checking out the repo
        uses: actions/checkout@master

      - name: Run container
        run: docker run -d -p 1080:1080 artemkaxboy/tor3proxy

      - name: Direct requests give same IPs
        run: |
          echo ::set-env name=direct_ip::$(./utils/get_ip.sh)
#          ip1=$(./utils/get_ip.sh)
#          ip2=$(./utils/get_ip.sh)
#          echo comparing "$ip1" and "$ip2"...
#          [[ "$ip1" != "$ip2" ]] && exit 1

      - name: Check anonymous proxy working
        run: |
          echo ::set-env name=proxy1_ip::$(./utils/get_ip.sh --proxy 1080)

      - name: Anonymous proxy gives different ip
        run: |
          [[ "${{ direct_ip }}" != "${{ proxy1_ip }}" ]] && exit 1
